services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4321:8080"
    environment:
      - CONTACT_EMAIL=${CONTACT_EMAIL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REFRESH_TOKEN=${GOOGLE_REFRESH_TOKEN}
      - GOOGLE_USER_EMAIL=${GOOGLE_USER_EMAIL}
    restart: unless-stopped
